//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weightlifting_Comp_Warmup.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int int_ProfileId {
            get {
                return ((int)(this["int_ProfileId"]));
            }
            set {
                this["int_ProfileId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_ProfileIds {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_ProfileIds"]));
            }
            set {
                this["ii_int_ProfileIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_string_ProfileName {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_string_ProfileName"]));
            }
            set {
                this["ii_string_ProfileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_BarbellWeight {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_BarbellWeight"]));
            }
            set {
                this["ii_int_BarbellWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_Snatch_SecondsStage {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_Snatch_SecondsStage"]));
            }
            set {
                this["ii_int_Snatch_SecondsStage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_Snatch_OpenerWeight {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_Snatch_OpenerWeight"]));
            }
            set {
                this["ii_int_Snatch_OpenerWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_Snatch_SecondsEnd {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_Snatch_SecondsEnd"]));
            }
            set {
                this["ii_int_Snatch_SecondsEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_Snatch_LiftsOut {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_Snatch_LiftsOut"]));
            }
            set {
                this["ii_int_Snatch_LiftsOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_CJ_SecondsStage {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_CJ_SecondsStage"]));
            }
            set {
                this["ii_int_CJ_SecondsStage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_CJ_OpenerWeight {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_CJ_OpenerWeight"]));
            }
            set {
                this["ii_int_CJ_OpenerWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_CJ_SecondsEnd {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_CJ_SecondsEnd"]));
            }
            set {
                this["ii_int_CJ_SecondsEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_CJ_LiftsOut {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_CJ_LiftsOut"]));
            }
            set {
                this["ii_int_CJ_LiftsOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_CJ_SecondsBreak {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_CJ_SecondsBreak"]));
            }
            set {
                this["ii_int_CJ_SecondsBreak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_CJ_SnatchLifts_Out {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_CJ_SnatchLifts_Out"]));
            }
            set {
                this["ii_int_CJ_SnatchLifts_Out"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_bool_Snatch_OpenerInWarmup {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_bool_Snatch_OpenerInWarmup"]));
            }
            set {
                this["ii_bool_Snatch_OpenerInWarmup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_bool_CJ_OpenerInWarmup {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_bool_CJ_OpenerInWarmup"]));
            }
            set {
                this["ii_bool_CJ_OpenerInWarmup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_bool_Beep {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_bool_Beep"]));
            }
            set {
                this["ii_bool_Beep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_SnatchExtras {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_SnatchExtras"]));
            }
            set {
                this["ii_strings_SnatchExtras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_SnatchJumps {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_SnatchJumps"]));
            }
            set {
                this["ii_strings_SnatchJumps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_SnatchTimes {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_SnatchTimes"]));
            }
            set {
                this["ii_strings_SnatchTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_CJExtras {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_CJExtras"]));
            }
            set {
                this["ii_strings_CJExtras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_CJJumps {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_CJJumps"]));
            }
            set {
                this["ii_strings_CJJumps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_CJTimes {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_CJTimes"]));
            }
            set {
                this["ii_strings_CJTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_hhmm_Start {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_hhmm_Start"]));
            }
            set {
                this["ii_hhmm_Start"] = value;
            }
        }
    }
}
