//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weightlifting_Comp_Warmup.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int int_Barbell {
            get {
                return ((int)(this["int_Barbell"]));
            }
            set {
                this["int_Barbell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int int_snatch_Sec_Stage {
            get {
                return ((int)(this["int_snatch_Sec_Stage"]));
            }
            set {
                this["int_snatch_Sec_Stage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int int_snatch_Wgt_Opener {
            get {
                return ((int)(this["int_snatch_Wgt_Opener"]));
            }
            set {
                this["int_snatch_Wgt_Opener"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int int_snatch_Sec_End {
            get {
                return ((int)(this["int_snatch_Sec_End"]));
            }
            set {
                this["int_snatch_Sec_End"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int int_snatch_Lifts_Out {
            get {
                return ((int)(this["int_snatch_Lifts_Out"]));
            }
            set {
                this["int_snatch_Lifts_Out"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int int_cj_Sec_Stage {
            get {
                return ((int)(this["int_cj_Sec_Stage"]));
            }
            set {
                this["int_cj_Sec_Stage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int int_cj_Wgt_Opener {
            get {
                return ((int)(this["int_cj_Wgt_Opener"]));
            }
            set {
                this["int_cj_Wgt_Opener"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int int_cj_Sec_End {
            get {
                return ((int)(this["int_cj_Sec_End"]));
            }
            set {
                this["int_cj_Sec_End"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int int_cj_Lifts_Out {
            get {
                return ((int)(this["int_cj_Lifts_Out"]));
            }
            set {
                this["int_cj_Lifts_Out"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> snatch_Extra {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["snatch_Extra"]));
            }
            set {
                this["snatch_Extra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> snatch_Jump {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["snatch_Jump"]));
            }
            set {
                this["snatch_Jump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> snatch_Time {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["snatch_Time"]));
            }
            set {
                this["snatch_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> cj_Extra {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["cj_Extra"]));
            }
            set {
                this["cj_Extra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> cj_Jump {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["cj_Jump"]));
            }
            set {
                this["cj_Jump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> cj_Time {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["cj_Time"]));
            }
            set {
                this["cj_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int int_cj_Sec_Break {
            get {
                return ((int)(this["int_cj_Sec_Break"]));
            }
            set {
                this["int_cj_Sec_Break"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int int_cj_snLifts_Out {
            get {
                return ((int)(this["int_cj_snLifts_Out"]));
            }
            set {
                this["int_cj_snLifts_Out"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_Beep {
            get {
                return ((bool)(this["bool_Beep"]));
            }
            set {
                this["bool_Beep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_snatch_OpenerWarmup {
            get {
                return ((bool)(this["bool_snatch_OpenerWarmup"]));
            }
            set {
                this["bool_snatch_OpenerWarmup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_cj_OpenerWarmup {
            get {
                return ((bool)(this["bool_cj_OpenerWarmup"]));
            }
            set {
                this["bool_cj_OpenerWarmup"] = value;
            }
        }
    }
}
