//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weightlifting_Comp_Warmup.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int int_ProfileId {
            get {
                return ((int)(this["int_ProfileId"]));
            }
            set {
                this["int_ProfileId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_ProfileIds {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_ProfileIds"]));
            }
            set {
                this["ii_int_ProfileIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_string_ProfileName {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_string_ProfileName"]));
            }
            set {
                this["ii_string_ProfileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_Barbell {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_Barbell"]));
            }
            set {
                this["ii_int_Barbell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_snatch_Sec_Stage {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_snatch_Sec_Stage"]));
            }
            set {
                this["ii_int_snatch_Sec_Stage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_snatch_Wgt_Opener {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_snatch_Wgt_Opener"]));
            }
            set {
                this["ii_int_snatch_Wgt_Opener"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_snatch_Sec_End {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_snatch_Sec_End"]));
            }
            set {
                this["ii_int_snatch_Sec_End"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_snatch_Lifts_Out {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_snatch_Lifts_Out"]));
            }
            set {
                this["ii_int_snatch_Lifts_Out"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_cj_Sec_Stage {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_cj_Sec_Stage"]));
            }
            set {
                this["ii_int_cj_Sec_Stage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_cj_Wgt_Opener {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_cj_Wgt_Opener"]));
            }
            set {
                this["ii_int_cj_Wgt_Opener"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_cj_Sec_End {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_cj_Sec_End"]));
            }
            set {
                this["ii_int_cj_Sec_End"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_cj_Lifts_Out {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_cj_Lifts_Out"]));
            }
            set {
                this["ii_int_cj_Lifts_Out"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_cj_Sec_Break {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_cj_Sec_Break"]));
            }
            set {
                this["ii_int_cj_Sec_Break"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_int_cj_snLifts_Out {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_int_cj_snLifts_Out"]));
            }
            set {
                this["ii_int_cj_snLifts_Out"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_bool_snatch_OpenerWarmup {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_bool_snatch_OpenerWarmup"]));
            }
            set {
                this["ii_bool_snatch_OpenerWarmup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_bool_cj_OpenerWarmup {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_bool_cj_OpenerWarmup"]));
            }
            set {
                this["ii_bool_cj_OpenerWarmup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_bool_Beep {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_bool_Beep"]));
            }
            set {
                this["ii_bool_Beep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_snatch_Extras {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_snatch_Extras"]));
            }
            set {
                this["ii_strings_snatch_Extras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_snatch_Jumps {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_snatch_Jumps"]));
            }
            set {
                this["ii_strings_snatch_Jumps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_snatch_Times {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_snatch_Times"]));
            }
            set {
                this["ii_strings_snatch_Times"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_cj_Extras {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_cj_Extras"]));
            }
            set {
                this["ii_strings_cj_Extras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_cj_Jumps {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_cj_Jumps"]));
            }
            set {
                this["ii_strings_cj_Jumps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_strings_cj_Times {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_strings_cj_Times"]));
            }
            set {
                this["ii_strings_cj_Times"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ii_HHmm_StartTimes {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ii_HHmm_StartTimes"]));
            }
            set {
                this["ii_HHmm_StartTimes"] = value;
            }
        }
    }
}
